spring:
  application:
    name: UpDown
  threads:
    virtual:
      enabled: true
storage:
  location: root
management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  show-actuator: false